#!/bin/bash
set -uo pipefail
shopt -s extglob

# Options or some shit like that
declare -r oscIP="127.0.0.1" # useful if sending to other device
declare -r oscPORT="9000"

# remove specific prefix from begining case and whitespace sensitive
declare -r rmBEGIN=(
    "Songs - "
    "Song - "
    "Music - "
    "not - "
)
# check with "playerctl -l", "firefox.instance_1_110", set prefered player
declare -r prefPLAYER="firefox"

get_media_info() {
    local PLAYER=()
    local get
    local state
    
    if [[ "$(pref_player_present)" == "true" ]]; then # sudo kill me
        PLAYER=(-p "$prefPLAYER")
    else
        PLAYER=()
    fi
    
    state="$(playerctl "${PLAYER[@]}" status)"

    if [[ "$state" == *"Paused"* ]]; then
        echo "Media paused"
        return
    fi
    get="$(playerctl "${PLAYER[@]}" metadata --format "{{title}} - {{artist}}")"
    get="$(clean_media_info "$get")"
    get="$(limiter2ln "$get")"
    echo "$get"
}

#deadass stupid
pref_player_present() {
    local players="$(playerctl -l)"
    if [[ $players == *$prefPLAYER* ]]; then
        echo "true"
    else
        echo "false"
    fi
}

# big thanks to that random guy that figure this out on a random forum  
clean_media_info() {
    local media="$1"
    
    for tmp_var_shit in "${rmBEGIN[@]}"; do
        if [[ "$media" == "$tmp_var_shit"* ]]; then 
            media="${media#"$tmp_var_shit"}"
        fi
    done

    while [[ "$media" == *\[*\]* ]]; do
        media="${media%%\[*\]*}${media#*\]*}"
    done

    media="${media##+([[:space:]])}"
    media="${media%%+([[:space:]])}"
    
    echo "$media"
}

limiter2ln() {
    local text="$1"
    local length=${#text}
    local maxLength=54 #vrc 27 max per line? i guess
    if [[ "$length" >="$maxLength" ]]; then
        text="${text:0:maxLength-3}..." #-3 to make space for ...
    fi
    echo "$text"
}

send_osc() {
    oscsend "$oscIP" "$oscPORT" /chatbox/input sTF "$1"
}

while true; do
    MESSAGE="$(date +%H:%M:%S)"$'\n'"$(get_media_info)"
    
    send_osc "$MESSAGE"
    
    echo "$MESSAGE"
    
    sleep 1.5
done